In [1]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [2]:
## create 2 empty list for storing the smaple & lable data for traing 

train_sample = []
train_lable = []

In [3]:
for i in range(1000):
    
    younger_age = randint(13,64)
    train_sample.append(younger_age)
    train_lable.append(0)
    
    older_age = randint(65,100)
    train_sample.append(older_age)
    train_lable.append(1)

In [4]:
train_lable

[0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,


In [5]:
train_sample

[30,
 88,
 40,
 65,
 39,
 68,
 26,
 66,
 53,
 84,
 34,
 83,
 41,
 74,
 54,
 87,
 38,
 78,
 25,
 89,
 23,
 83,
 33,
 91,
 48,
 79,
 42,
 69,
 26,
 89,
 33,
 67,
 62,
 68,
 21,
 76,
 58,
 98,
 27,
 75,
 55,
 66,
 32,
 87,
 28,
 67,
 44,
 98,
 17,
 84,
 35,
 68,
 54,
 83,
 26,
 93,
 40,
 69,
 44,
 78,
 64,
 66,
 44,
 88,
 52,
 100,
 51,
 71,
 44,
 83,
 27,
 71,
 52,
 76,
 54,
 91,
 19,
 73,
 30,
 72,
 54,
 93,
 33,
 71,
 24,
 95,
 23,
 65,
 64,
 90,
 16,
 93,
 33,
 79,
 19,
 76,
 55,
 85,
 52,
 72,
 61,
 68,
 40,
 74,
 36,
 84,
 27,
 74,
 19,
 88,
 32,
 91,
 33,
 70,
 48,
 83,
 28,
 69,
 23,
 82,
 32,
 96,
 14,
 79,
 17,
 86,
 39,
 98,
 28,
 74,
 53,
 75,
 28,
 94,
 59,
 78,
 51,
 82,
 48,
 67,
 42,
 87,
 18,
 75,
 64,
 89,
 30,
 83,
 29,
 89,
 63,
 73,
 17,
 86,
 50,
 77,
 22,
 91,
 47,
 100,
 58,
 97,
 55,
 68,
 54,
 82,
 32,
 67,
 52,
 84,
 36,
 87,
 24,
 99,
 16,
 69,
 32,
 86,
 37,
 87,
 26,
 90,
 40,
 96,
 26,
 93,
 56,
 91,
 55,
 74,
 34,
 86,
 59,
 70,
 47,
 91,
 64,
 67,
 27,
 87

In [6]:
train_lable = np.array(train_lable)

train_sample = np.array(train_sample)

In [7]:
train_lable

array([0, 1, 0, ..., 1, 0, 1])

In [8]:
train_sample

array([30, 88, 40, ..., 79, 20, 88])

In [9]:
scaler = MinMaxScaler()
scaler_train_sample = scaler.fit_transform(train_sample.reshape(-1,1))

In [10]:
scaler_train_sample

array([[0.1954023 ],
       [0.86206897],
       [0.31034483],
       ...,
       [0.75862069],
       [0.08045977],
       [0.86206897]])

In [18]:
import keras
from keras.layers import Dense
from keras.models import Sequential
from keras.optimizers import Adam

In [19]:
model = Sequential([Dense(units = 16, input_dim = 1, activation= 'relu', ),
                    Dense(32, activation= 'relu'),
                    Dense(2, activation= 'softmax')])

In [20]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 16)                32        
                                                                 
 dense_4 (Dense)             (None, 32)                544       
                                                                 
 dense_5 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [25]:
## compile the model

model.compile(Adam(learning_rate= 0.001), loss = 'sparse_categorical_crossentropy', metrics= ['accuracy'])

In [26]:
model.fit(train_sample, train_lable, batch_size= 10, epochs= 10)

Epoch 1/10
200/200 [==============================] - 5s 3ms/step - loss: 0.6076 - accuracy: 0.6115
Epoch 2/10
200/200 [==============================] - 0s 2ms/step - loss: 0.4816 - accuracy: 0.7840
Epoch 3/10
200/200 [==============================] - 0s 2ms/step - loss: 0.3852 - accuracy: 0.8735
Epoch 4/10
200/200 [==============================] - 1s 3ms/step - loss: 0.3080 - accuracy: 0.9115
Epoch 5/10
200/200 [==============================] - 0s 2ms/step - loss: 0.2632 - accuracy: 0.9220
Epoch 6/10
200/200 [==============================] - 0s 2ms/step - loss: 0.2220 - accuracy: 0.9405
Epoch 7/10
200/200 [==============================] - 0s 2ms/step - loss: 0.1980 - accuracy: 0.9415
Epoch 8/10
200/200 [==============================] - 0s 2ms/step - loss: 0.1720 - accuracy: 0.9535
Epoch 9/10
200/200 [==============================] - 0s 2ms/step - loss: 0.1632 - accuracy: 0.9560
Epoch 10/10
200/200 [==============================] - 0s 2ms/step - loss: 0.1371 - accuracy: 0.9630

In [30]:
## for test dataset 

test_samples = []
test_labels = []

for i in range(500):
    
    younger_age = randint(13,64)
    test_samples.append(younger_age)
    test_labels.append(0)
    
    older_age = randint(65,100)
    test_samples.append(older_age)
    test_labels.append(1)

In [31]:
test_labels = np.array(test_labels)

test_samples = np.array(test_samples)

In [32]:
scaler_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

In [33]:
scaler_test_samples

array([[0.2183908 ],
       [0.72413793],
       [0.25287356],
       [0.71264368],
       [0.16091954],
       [0.82758621],
       [0.45977011],
       [0.7816092 ],
       [0.06896552],
       [0.81609195],
       [0.56321839],
       [0.88505747],
       [0.42528736],
       [0.72413793],
       [0.14942529],
       [0.85057471],
       [0.34482759],
       [0.74712644],
       [0.37931034],
       [0.71264368],
       [0.20689655],
       [0.83908046],
       [0.22988506],
       [0.77011494],
       [0.52873563],
       [0.71264368],
       [0.01149425],
       [0.87356322],
       [0.42528736],
       [0.81609195],
       [0.09195402],
       [0.90804598],
       [0.51724138],
       [0.77011494],
       [0.47126437],
       [0.90804598],
       [0.04597701],
       [0.95402299],
       [0.47126437],
       [0.77011494],
       [0.16091954],
       [0.85057471],
       [0.06896552],
       [0.72413793],
       [0.25287356],
       [0.72413793],
       [0.06896552],
       [0.666

In [38]:
## predict the value using test samples

test_sample_output = model.predict(test_samples, batch_size= 10)

100/100 [==============================] - 0s 2ms/step


In [42]:
model.evaluate(test_samples,test_labels)[1]

32/32 [==============================] - 0s 2ms/step - loss: 0.1134 - accuracy: 0.9640


0.9639999866485596

In [ ]:
model.predict_cla()

In [39]:
test_sample_output

array([[0.99125403, 0.00874598],
       [0.07967108, 0.920329  ],
       [0.98581135, 0.01418864],
       ...,
       [0.00537914, 0.9946208 ],
       [0.61994267, 0.38005728],
       [0.00330442, 0.99669564]], dtype=float32)

In [43]:
from sklearn.metrics import confusion_matrix

# matrix_value = confusion_matrix(test_sample_output, test_labels)